apiVersion: v1
kind: Service
metadata:
    name: "k1-3e49"
    labels:
        app: "k1-3e49"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "k1-3e49"